name: snapshot

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GORELEASER_CURRENT_TAG: "0.0.9" # any sem ver tag to bypass goreleaser semver check

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
          workdir: server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: snapshot release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: |
            server/dist/guppyflo_x86_64.zip
            server/dist/guppyflo_armv6.zip
            server/dist/guppyflo_mipsle.zip
            server/dist/guppyflo_windows_x86_64.zip
          fail_on_unmatched_files: true
